env:
  global:
    - CC_TEST_REPORTER_ID=b7a6b75f5c24a952363e02793dfa149835a1c7e734afb8c9222c8018cae3c72d
language: ruby
rvm:
  - 2.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
